### ISSUE TITLE
plugin is broken in elgg 2.0.x

### ISSUE THREAD

**Issue by propertunist** [Elggzone/River-Addon#10]
i just came to test the 1.9 version of river addon in elgg 2.0.3 and found the following:

* the location of the river.php page has changed, so references need to be updated to reflect that
* the sidebars on the activity page are empty
* the page_type variable is not being passed through to river.php

since i use river addon on my live site and am in the process of upgrading to elgg 2.0.3, i would appreciate an ETA for a new release for this plugin. thanks

**Comment by PerJensen** [comment]
Thanks @propertunist. This repo is not updated any more. Try the latest river addon available on my website. It's for 2.0, early 2.0 though, try it out please.

**Comment by propertunist** [comment]
aha, ok - thanks. i just tested the 2.0 version and now i can see the various side modules correctly. i'll do some more testing and see how it goes.
